name: "ci-cd pipeline"

on: workflow_dispatch

  # push:
  #   branches:
  #   - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: website/package-lock.json
    - name: Install dependencies
      run: npm install
      working-directory: website
    - name: Build file
      run: npm run build
      working-directory: website
      
      
    - name: Deploy production to Netlify
      uses: South-Paw/action-netlify-deploy@v1.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
        build-dir: './website/build'
        comment-on-commit: true